spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yaml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1012196860639-d4t1tfo8ctsgp8t6e6m3nr3ghohrgidh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "${BASE_URL}/login/oauth2/code/google"
  ai:
    openai:
      model: gpt-3.5-turbo
      api-key: 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
logging:
  level:
    root: ERROR

gladia:
  create-request:
    cron: "0 * * * * ?"
  get-response:
    cron: "0 */5 * * * ?"
  api:
    key: a37d25af-66b4-4744-ac18-5b725cc3c6b8

llm:
  generate-lesson:
    cron: "0 * * * * ?"

lesson:
  ready-lesson:
    cron: "0 * * * * ?"

app:
  frontend-url: ${FRONTEND_URL}
  jwt:
      expiration-seconds: 604800
      secret-base64: a1b2C3D4E5F6g7h8i9j0K1L2M3N4O5P6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2

server:
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto