spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real_talk
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/real_talk
    user: postgres
    password: postgres
    change-log: classpath:/db/changelog/changelog.yaml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1012196860639-d4t1tfo8ctsgp8t6e6m3nr3ghohrgidh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  ai:
    openai:
      model: gpt-3.5-turbo
      api-key: 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
logging:
  level:
    root: INFO

gladia:
  create-request:
    cron: "0 * * * * ?"
  get-response:
    cron: "0 */5 * * * ?"
  api:
    key: a37d25af-66b4-4744-ac18-5b725cc3c6b8

llm:
  generate-lesson:
    cron: "0 * * * * ?"

lesson:
  ready-lesson:
    cron: "0 * * * * ?"

app:
  frontend-url: http://localhost:3000